### PR TITLE
Transpile esm and cjs formats to es5

### LINKED ISSUE #73: Version 1.7.2 causing errors in IE11
We've tried to upgrade vuex-persist to version 1.7.2 from 1.5.3 but we're seeing the following error in Internet Explorer 11 only (not seeing in other browsers):

SCRIPT1002: Syntax error
 "./node_modules/vuex-persist/dist/esm/index.js"

/**
 * Created by championswimmer on 22/07/17.
 */
let MockStorage;
// @ts-ignore
{
    MockStorage = class { **<= Error is thrown here** 
        get length() {
            return Object.keys(this).length;
        }

We're using Vue v2.5.17 and Vuex v3.0.1.

### PR DESCRIPTION
**Pull request by hiendv**
Fix #73

### CODE REVIEW

**Comment by championswimmer** [comment]
cjs and esm modules are supposed to pass through the end-users own build setup. if he/she uses babel and choses to transpile it to es5 it'll happen so, if not, it is upto them.

**Comment by shannonsands** [comment]
Same issue -
Unexpected token: name (MockStorage) [./~/vuex-persist/dist/esm/index.js:6,0]

Just using a vue-cli generated project. Have set it up to transpile it through now, but seconding that best practice is to not assume end users (especially when new to Javascript) have remembered to configure babel just for your module (since this is NOT a usual practice), or when using a common toolchain (especially a preconfigured one like vue-cli). Convention over configuration please.

**Comment by hiendv** [comment]
Try setting `transpileDependencies` option in vue.config.js

**Comment by championswimmer** [comment]
Okay I discussed with some other library authors. Will transpile this to
ES5 for cjs.

**Comment by hiendv** [comment]
Sorry but why not also `esm`?

**Comment by hiendv** [comment]
Release it, please?

**Comment by hiendv** [comment]
Release it, please?

**Comment by hiendv** [comment]
Release it, please?

**Comment by hiendv** [comment]
Release it, please?

**Comment by hiendv** [comment]
Release it, please?

**Comment by AlanMacdonald** [comment]
What's going on with this,we still get the same error?  We have to keep holding back npm updates of vuex when upgrading all our other packages because of lack of IE11 support when we have ~20k users using that browser.  Are we still saying we have to setup transpilation ourselves?

**Pull request merged**
